### ISSUE TITLE
bug(revision): error on file change

### ISSUE THREAD

**Issue by rbarilani** [bhaskarmelkani/hexo-asset-pipeline#2]
Hi @bhaskarmelkani, on hexo server (when a file change), I got this error:

```
Unhandled rejection TypeError: Cannot read property 'revIndex' of undefined
    at Hexo.run (/Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/hexo-asset-pipeline/lib/revision.js:29:38)
    at Hexo.tryCatcher (/Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/bluebird/js/release/method.js:15:34)
    at /Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/hexo/lib/extend/filter.js:68:35
    at tryCatcher (/Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/bluebird/js/release/reduce.js:155:18)
    at Object.gotAccum (/Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/bluebird/js/release/promise.js:638:18)
    at MappingPromiseArray.PromiseArray._resolve (/Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/bluebird/js/release/promise_array.js:126:19)
    at MappingPromiseArray._promiseFulfilled (/Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/bluebird/js/release/map.js:101:18)
    at Promise._settlePromise (/Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/bluebird/js/release/promise.js:574:26)
```

**Comment by bhaskarmelkani** [comment]
Hey @rbarilani , this was fixed in [commit](https://github.bus.zalan.do/merchant-center/merchant-center-documentation/pull/37)
