### ISSUE TITLE
refactor(plugin): plugin fails to load if no config provided

### ISSUE THREAD

**Issue by rbarilani** [bhaskarmelkani/hexo-asset-pipeline#3]
Plugin fails to load if no config provided.. would  be a good idea providing defaults?

Here the stack trace:

```
ERROR Plugin load failed: hexo-asset-pipeline
TypeError: Cannot read property 'clean_css' of undefined
    at /Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/hexo-asset-pipeline/index.js:14:109
    at /Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/hexo/lib/hexo/index.js:232:12
    at tryCatcher (/Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/bluebird/js/release/promise.js:638:18)
    at /Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/rbarilani/Workspaces/stargate/merchant-center-documentation/node_modules/graceful-fs/graceful-fs.js:78:16
    at tryToString (fs.js:448:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:435:12)
```

**Comment by bhaskarmelkani** [comment]
I have added a check to not load plugin if there is no root config element(`undefined === hexo.config.asset_pipeline`).

[#commit](https://github.com/bhaskarmelkani/hexo-asset-pipeline/commit/e479841e4ddb2d66b7ec35058900561d7e67770f)

**Comment by rbarilani** [comment]
@bhaskarmelkani And what if I have `hexo.config.asset_pipeline` but not the `hexo.config.asset_pipeline.clean_css`?

**Comment by bhaskarmelkani** [comment]
The pipeline will run with default settings for each  plugin. For `clean_css` its `exclude: ['*.min.css']`.
