### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict

### ISSUE THREAD

**Issue by wololock** [bhaskarmelkani/hexo-asset-pipeline#8]
Hexo version: 3.3.9
hexo-asset-pipeline version: 1.2.5

Running `hexo clean` and `hexo generate` causes `ERROR Plugin load failed: hexo-asset-pipeline`

**Full error log:**
```
ERROR Plugin load failed: hexo-asset-pipeline
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/wololock/workspace/wololock.github.io/node_modules/hexo-asset-pipeline/lib/filters/index.js:1:76)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/home/wololock/workspace/wololock.github.io/node_modules/hexo/lib/hexo/index.js:216:21)
    at /home/wololock/workspace/wololock.github.io/node_modules/hexo-asset-pipeline/index.js:1:82
    at /home/wololock/workspace/wololock.github.io/node_modules/hexo/lib/hexo/index.js:232:12
    at tryCatcher (/home/wololock/workspace/wololock.github.io/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/wololock/workspace/wololock.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/wololock/workspace/wololock.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/wololock/workspace/wololock.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/wololock/workspace/wololock.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/wololock/workspace/wololock.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:638:18)
```

**package.json**

```
{
  "name": "sitename",
  "version": "1.0.0",
  "private": true,
  "hexo": {
    "version": "3.3.9"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-asset-pipeline": "^1.2.5",
    "hexo-browsersync": "^0.2.0",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-cname": "^0.3.0",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-jade": "^0.4.1",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-sass": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0"
  }
}
```

**Comment by bhaskarmelkani** [comment]
Hey,
Looking into it. Will fix ASAP.
Meanwhile can you tell me the version of Node on which you are running it ?

**Comment by bhaskarmelkani** [comment]
Hey,

I updated the code and already pushed to npm.

Did you have a chance try it out ?

**Comment by bhaskarmelkani** [comment]
Closing due to inactivity.
